Try to use env variables
Because i somehow get this error for the previous version:
```
ParserError: D:\a\_temp\e529698e-979c-4c70-9fd6-14fd79341ee1.ps1:2
Line |
   2 |  $folders = '',
     |             ~~
     | The assignment expression is not valid. The input to an assignment operator must be an object that is
     | able to accept assignments, such as a variable or a property.
```